/*
* File: main.c
*
* C/C++ source code generated on  : Thu Jun 4 11:12:24 2015
* C/C++ source code generated by  : Alireza Ramezani, Champaign-Urbana-IL
* Target selection: stm32F4xx.tlc
* Embedded hardware selection: STMicroelectronics->STM32F4xx 32-bit Cortex-M4
* Code generation objectives:
*    1. Execution efficiency
*    2. ROM efficiency
*    3. RAM efficiency
*    4. Traceability
*    5. Safety precaution
*    6. Debugging
*    7. MISRA-C:2004 guidelines
*    8. Polyspace Model Link for Simulink
* Validation result: Passed (14), Warnings (2), Error (1)
*
*
*
* ******************************************************************************
* * attention
* *
* * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
* * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
* * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
* * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
* * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
* * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
* *
* ******************************************************************************
*/

#include <stdio.h>
#include "VN_lib.h"
#include "VN_user.h"
#include "stddef.h"
#include "stm32f4xx.h"
#include "daq.h"
#include "controller.h"
#include "rtwtypes.h"
#include "debug.h"
#include "as5048b.h"
#include "interface_board.h"

/* DAQ and controller loop at 1.0 KHz */
#define SAMPLE_TIME 0.01

/* Uncomment for debug msg over USART port */
#define DEBUG_MAIN

/* this variable is used to create a time reference incremented by 1 mili-second */
//#define SYSTEMTICK_PERIOD_MS 0.1

/* this variables are used to allocate a timer for the main application */
#define MAIN_TIM TIM7
#define MAIN_RCC_APBPeriph RCC_APB1Periph_TIM7

/* RCC_Configuration defined in RCC_Configuration.c file */
/* Clock configuration function provided as example */
extern void RCC_Configuration(void);

/* Real-time model */
extern RT_MODEL_daq *const daq_M;

/* Set which subrates need to run this base step (base rate always runs).*/
/* Defined in daq.c file */
extern void daq_SetEventsForThisBaseStep(boolean_T*);

/* Flags for taskOverrun */
static boolean_T OverrunFlags[1];

/* Number of auto reload timer rotation computed */
static uint32_t autoReloadTimerLoopVal_S = 1;

/* Remaining number of auto reload timer rotation to do */
static uint32_t remainAutoReloadTimerLoopVal_S = 1;

/* PWM duty cicle to PA3, PB1, PE5, PE6 */
int16_T _pwm_pa3;
int16_T _pwm_pb1;
int16_T _pwm_pe5;
int16_T _pwm_pe6;

/* Private functions */
void main_delay_us(unsigned long us);
void main_delay_ms(unsigned long ms);
void main_initialize_us_timer(void);

/****************************************************
SysTick_Handler function
This handler is called every tick and schedules tasks
*****************************************************/
void SysTick_Handler(void)
{
	/* Manage nb of loop before interrupt has to be processed */
	remainAutoReloadTimerLoopVal_S--;
	if (remainAutoReloadTimerLoopVal_S) {
		return;
	}

	remainAutoReloadTimerLoopVal_S = autoReloadTimerLoopVal_S;

	/* Check base rate for overrun */
	if (OverrunFlags[0]) {
		rtmSetErrorStatus(daq_M, "Overrun");
		return;
	}

	OverrunFlags[0] = true;
	
	/* read encoders */
	uint16_t angleReg[4] = {0,0,0,0};
	uint8_t autoGain[4] = {0, 0, 0, 0};
	uint8_t diag[4] = {0, 0, 0, 0};
	uint16_t magnitude[4] = {0, 0, 0, 0};
	double angle[4] = {0, 0, 0, 0};
	AS5048B_readBodyAngles(angleReg, autoGain, diag, magnitude, angle);
	
	/* vn100 read yaw, pitch, and roll */
	VN100_SPI_Packet *packet;
	float yaw, pitch, roll;
	packet = VN100_SPI_GetYPR(0, &yaw, &pitch, &roll);
	//roll = 0;
	//pitch = 0;
	//yaw = 0;
	
	/* inpute to controller here */
	controller_U.pid_gian[0]; // forelimb Kp -200
	controller_U.pid_gian[1] = 200; // leg Kp
	controller_U.pid_gian[2]; // forelimb Kd -60
	controller_U.pid_gian[3] = 20; // leg Kd
	controller_U.pid_gian[4]; // forelimb Ki ???
	controller_U.pid_gian[5] = 0; // leg Ki ???
	controller_U.actuator_ctrl_params[0]; // PID_SATURATION_THRESHOLD [pwm] (control sat, used in pid func)
	controller_U.actuator_ctrl_params[1] = 20; // MAX_ANGLE_DIFFERENCE [deg\sec] (used in anti-roll-over func)
	controller_U.actuator_ctrl_params[2] = 360; // ANTI_ROLLOVER_CORRECTION [deg] (used in anti-roll-over func)
	controller_U.actuator_ctrl_params[3] = 308; // MAX_RP_ANGLE_RIGHT [deg] 
	controller_U.actuator_ctrl_params[4] = 180; // MAX_DV_ANGLE_RIGHT [deg]
	controller_U.actuator_ctrl_params[5] = 240; // MIN_RP_ANGLE_RIGHT [deg]
	controller_U.actuator_ctrl_params[6] = 130; // MIN_DV_ANGLE_RIGHT [deg]
	controller_U.actuator_ctrl_params[7] = 243; // MAX_RP_ANGLE_LEFT [deg]
	controller_U.actuator_ctrl_params[8] = 130; // MAX_DV_ANGLE_LEFT [deg]
	controller_U.actuator_ctrl_params[9] = 185; // MIN_RP_ANGLE_LEFT [deg]
	controller_U.actuator_ctrl_params[10] = 70; // MIN_DV_ANGLE_LEFT [deg]
	controller_U.actuator_ctrl_params[11] = SAMPLE_TIME; // Sample interval
	controller_U.flight_ctrl_params[0] = -0.01; // ROLL_SENSITIVITY [-]
	controller_U.flight_ctrl_params[1] = 0.001;  // PITCH_SENSITIVITY [-]
	controller_U.flight_ctrl_params[2] = 0.0;  // MAX_FORELIMB_ANGLE [deg] (n.a.)
	controller_U.flight_ctrl_params[3] = 0.0;  // MIN_FORELIMB_ANGLE [deg] (n.a.)
	controller_U.flight_ctrl_params[4] = 0.0;  // MAX_LEG_ANGLE [deg] (n.a.)
	controller_U.flight_ctrl_params[5] = 0.0;  // MIN_LEG_ANGLE [deg] (n.a.)
	
	// oscillating equilibrium point
	static float oscillating_freq;
	static float oscillating_amp;
	static float oscillating_offset;
	float oscillating_eq = 0;
	oscillating_eq = oscillating_amp*sin(2*PI*oscillating_freq*controller_Y.time) + oscillating_offset;
	controller_U.flight_ctrl_params[6] = RAD2DEG(oscillating_eq);  // R_foreq  [deg]
	controller_U.flight_ctrl_params[7] = 30;  // L_foreq [deg]
	controller_U.flight_ctrl_params[8] = 32;  // R_leq [deg]
	controller_U.flight_ctrl_params[9] = 28;  // L_leq [deg]
	
	// IMU
	controller_U.roll = roll;
	controller_U.pitch = pitch;
	controller_U.yaw = yaw;
	//controller_U.roll = 0;
	//controller_U.pitch = 0;
	//controller_U.yaw = 0;
	
	// Encoders
	controller_U.angle[0] = angle[0]; // Right forelimb
	controller_U.angle[1] = angle[2]; // Left forelimb
	controller_U.angle[2] = angle[2]; // Right tail
	controller_U.angle[3] = angle[0]; // Left tail (using right forelimb encoder!)
	
	/* Step the controller for base rate */
	controller_step();
		
	/* drv8835 commands */
	daq_U.pwm_pa6; // Right forelimb 
	daq_U.pwm_pa7 = controller_Y.M0A;
	daq_U.pwm_pb0; // Left forelimb
	_pwm_pb1 = controller_Y.M1B;
	daq_U.pwm_pa0; // Right leg
	daq_U.pwm_pa1 = controller_Y.M2B;
	daq_U.pwm_pa2; // Left leg
	_pwm_pa3 = controller_Y.M3A;
	
	/* TMS320 commands*/
	_pwm_pe5 = controller_Y.ubldc[0];	// right armwing
	_pwm_pe6 = controller_Y.ubldc[1];	// left armwing
	
	
	/* Step the model for base rate */
	daq_step();
	INTERFACE_BOARD_pwmGenerator();
	
	char Buff [] = "                                                                                                                                           \r\n\0";
	//const char *tmpBuff = "roll = %f, pitch = %f, yaw = %f";
	//sprintf(Buff, tmpBuff, controller_Y.q[0], controller_Y.q[1], controller_Y.q[2]);
	//debug_printf(Buff, 144);
	//
	const char *tmpBuff = "mag1 = %d, mag2 = %d, mag3 = %d,  mag4 = %d";
	sprintf(Buff, tmpBuff, autoGain[0], autoGain[1], autoGain[2], autoGain[3]);
	debug_printf(Buff, 144);
	
	//const char *tmpbuff = "angle1 = %f, angle2 = %f, angle3 = %f,  angle4 = %f";
	//sprintf(Buff, tmpbuff, angle[0], angle[1], angle[2], angle[3]);
	//debug_printf(Buff, 144);
	
	//const char *tmpbuff = "bldc[0] = %f, bldc[1] = %f, bldc[2] = %f,  bldc[3] = %f";
	//sprintf(Buff, tmpbuff, controller_Y.ubldc[0], controller_Y.ubldc[1], controller_Y.ubldc[2], controller_Y.ubldc[3]);
	//debug_printf(Buff, 144);
	
	
	//const char *tmpBuff = "debug1 = %f, debug2 = %f, debug3 = %f,  debug4 = %f";
	//sprintf(Buff, tmpBuff, controller_Y.debug[0], controller_Y.debug[1], controller_Y.debug[2], controller_Y.debug[3]);
	//debug_printf(Buff, 144);
	
	//const char *tmpBuff = "time = %f, eq = %f, angle = %f,  controller = %f";
	//sprintf(Buff, tmpBuff, controller_Y.time, oscillating_eq, controller_Y.debug[0], controller_Y.ubldc[0]);
	//debug_printf(Buff, 144);
	
	
	/* Indicate task for base rate complete */
	OverrunFlags[0] = false;
}

/****************************************************
main function
Example of main :
- Clock configuration
- call Initialize
- Wait for systick (infinite loop)
*****************************************************/
int main (void)
{

	/* Data initialization */
	int_T i;
	for (i=0;i<1;i++) {
		OverrunFlags[i] = 0;
	}

	/* Clock has to be configured first*/
	RCC_Configuration();

	/* Initilaize the main application timer */
	main_initialize_us_timer();

	/* Model initialization call */
	daq_initialize();
	INTERFACE_BOARD_initialize();
	
	/* controller initialization call */
	controller_initialize();
	
	/* vn100 spi initialization */
	SPI_initialize();	
	
	/* tare imu */
	VN100_SPI_Tare(0);
	
	/* initialize encoders */
	AS5048B_initialize();

	/* Systick configuration and enable SysTickHandler interrupt */
	float dt = SAMPLE_TIME;
	if (SysTick_Config((uint32_t)(SystemCoreClock * dt))) {
		autoReloadTimerLoopVal_S = 1;
		do {
			autoReloadTimerLoopVal_S++;
		} while ((uint32_t)(SystemCoreClock * dt)/autoReloadTimerLoopVal_S >
			SysTick_LOAD_RELOAD_Msk);

		SysTick_Config((uint32_t)(SystemCoreClock * dt)/autoReloadTimerLoopVal_S);
	}

	remainAutoReloadTimerLoopVal_S = autoReloadTimerLoopVal_S;//Set nb of loop to do

	/* Infinite loop */
	/* Real time from systickHandler */
	while (1) 
	{
	}	
}

/*******************************************************************************
* Function Name  : main_delay_us
* Input          : 
* Output         : None
* Return         : 
* Description    : 
*******************************************************************************/

void main_delay_us(unsigned long us)
{
	uint16_t t0 = MAIN_TIM->CNT;
	for (;;) {
		int t = MAIN_TIM->CNT;
		if (t < t0){
			t += 0x10000;
		}

		if (us < t - t0)
			return;

		us -= t - t0;
		t0 = t;
	}
}


/*******************************************************************************
* Function Name  : main_delay_ms
* Input          : 
* Output         : None
* Return         : 
* Description    : 
*******************************************************************************/

void main_delay_ms(unsigned long ms)
{
	main_delay_us(ms * 1000);
}


/*******************************************************************************
* Function Name  : main_initialize_us_timer
* Input          : 
* Output         : None
* Return         : 
* Description    : 
*******************************************************************************/

void main_initialize_us_timer()
{
	RCC_ClocksTypeDef RCC_Clocks;
	RCC_GetClocksFreq(&RCC_Clocks);

	RCC->APB1ENR |= MAIN_RCC_APBPeriph;
	MAIN_TIM->PSC = (RCC_Clocks.PCLK1_Frequency / 1000000) - 1;
	MAIN_TIM->ARR = 0xFFFF;
	MAIN_TIM->CR1 = TIM_CR1_CEN;
}



/* File trailer for Real-Time Workshop generated code.
*
* [EOF] main.c
*/
